import localFont from "next/font/local";
import "./globals.css";
import {Inter } from 'next/font/google';
import SparklesIcon from "@/components/SparklesIcon";

import Link from 'next/link';

const inter =Inter({subsets:['latin']})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${inter.className} bg-gradient-to-b from-bg-gradient-from to-bg-gradient-to min-h-screen text-white`}
      >
        <main className="p-4 max-w-2xl mx-auto">
        <header className="flex justify-between my-8">
        <Link href="/" className="flex gap-1">
         <SparklesIcon />
        </Link>
        <nav className="flex gap-6 text-white/80">
          <Link href="/">Home</Link>
          <Link href="/Pricing">Pricing</Link>
          <Link href="mailto:conatact@epiccaptions.com">Contact</Link>
        </nav>
      </header>
        {children}

        </main>
      </body>
    </html>
  );
}
